### ISSUE TITLE
terminate called after throwing an instance of 'std::invalid_argument'   what():  stoi

### ISSUE THREAD

**Issue by p719967821** [TrustworthyComputing/REDsec#1]
![image](https://github.com/user-attachments/assets/cca79c25-87c1-4fd1-8314-e8b32dff7055)
When I run make gpu-encrypt, this problem occurs. What is the matter?

**Comment by cgouert** [comment]
I can't seem to replicate the issue; did you generate the keypair with `make redcufhe-keygen` and encrypted image with `make redcufhe-encrypt-image` in the client directory?

**Comment by p719967821** [comment]
Sorry, I found that this problem was caused by my misoperation. I didn't execute the keygen and encrypt-image of the gpu version before.
In addition, I'm very grateful for your open source code and your timely reply. This is really a great open source library.

**Comment by cgouert** [comment]
Glad it was a simple fix; thank you very much!
